$(eval $(call PackageDir,luci-app-ssr-plus,luci-app-ssr-plus,))
$(eval $(call PackageDir,naiveproxy,naiveproxy,))
$(eval $(call PackageDir,shadowsocks-rust,shadowsocks-rust,))
$(eval $(call PackageDir,tcping,tcping,))
$(eval $(call PackageDir,xray-core,xray-core,))
$(eval $(call PackageDir,xray-plugin,xray-plugin,))
